AWSTemplateFormatVersion: 2010-09-09
Description: visitor-management
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  CognitoDomainPrefix:
    Type: String
    Default: login
    Description: The Cognito User Pool domain prefix
  AcmCertificateArn:
    Type: String
    Default: arn:aws:acm:us-east-1:121216464768:certificate/4f441ddb-b0d2-493d-b2d0-e5b3ed387553
    Description: The public certificate arn in us-east-1 region
  AdminGroupName:
    Type: String
    Default: admin
    Description: Name of the admin user group in Verified Permissions
  ResidentGroupName:
    Type: String
    Default: resident
    Description: Name of the resident user group in Verified Permissions
  GuardGroupName:
    Type: String
    Default: guard
    Description: Name of the guard user group in Verified Permissions

Resources: !Include resources/verified-permissions.yaml
  !Include resources/api-gateway.yaml
  !Include resources/lambda-functions.yaml
  !Include resources/dynamo-db-tables.yaml
  !Include resources/s3-cloudfront.yaml
  !Include resources/cognito.yaml

Outputs:
  APIGatewayEndpoint: !GetAtt ApiGatewayApi.Outputs.Endpoint
  CloudFrontDistributionId:
    Description: CloudFront Distribution ID for hosting web front end
    Value: !Ref CloudFrontDistribution
  CloudFrontDistributionDomainName:
    Description: CloudFront Distribution Domain Name for accessing web front end
    Value: !GetAtt CloudFrontDistribution.DomainName
  WebS3BucketName:
    Description: S3 Bucket for hosting web frontend
    Value: !Ref WebSiteBucket
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref CognitoUserPoolClient
  UserPoolDomainUrl:
    Description: Cognito User Pool Domain URL
    Value: !Sub https://${CognitoDomainPrefix}.auth.${AWS::Region}.amazoncognito.com
  AuthorityUrl:
    Description: Cognito User Pool Authority URL (for OIDC client)
    Value: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON
