AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Api Gateway resource

Resources:
  ApiGatewayApiNew:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      TracingEnabled: true
      Cors:
        AllowMethods: "'OPTIONS,POST,GET'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'https://vms.alphinecodetech.click'"
        AllowCredentials: true

Outputs:
  ApiGatewayApiNew:
    Value: !Ref ApiGatewayApiNew
