AWSTemplateFormatVersion: "2010-09-09"
Description: Nested stack for Cognito User Pool and User Groups

Parameters:
  AdminGroupName:
    Type: String
  ResidentGroupName:
    Type: String
  GuardGroupName:
    Type: String

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: VisitorManagementCognitoUserPool #TODO: base on stack name
      Schema:
        - Name: "given_name"
          Required: true
          Mutable: true
        - Name: "family_name"
          Required: true
          Mutable: true
        - Name: "email"
          Required: true
          Mutable: true
        - Name: "phone_number"
          Required: false
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      # DeletionProtection: ACTIVE

  AdminUserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: !Ref AdminGroupName
      UserPoolId: !Ref CognitoUserPool
      Description: Admin users
      Precedence: 0

  ResidentUserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: !Ref ResidentGroupName
      UserPoolId: !Ref CognitoUserPool
      Description: Resident users
      Precedence: 1

  GuardUserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: !Ref GuardGroupName
      UserPoolId: !Ref CognitoUserPool
      Description: Guard users
      Precedence: 2

Outputs:
  CognitoUserPool:
    Value: !Ref CognitoUserPool
    Export:
      Name: CognitoUserPool
