AWSTemplateFormatVersion: "2010-09-09"
Description: Nested stack for Hosted Zone RecordSet

Parameters:
  GlobalCloudFrontHostedZoneId:
    Type: String
  HostedZoneId:
    Type: String
  CognitoCustomDomainName:
    Type: String

Resources:
  CloudFrontTypeARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: vms.alphinecodetech.click
      Type: A
      AliasTarget:
        HostedZoneId: !Ref GlobalCloudFrontHostedZoneId
        DNSName: !ImportValue CloudFrontDistributionDomainName
        EvaluateTargetHealth: false # Important for CloudFront

  CloudFrontLoginVMSCNAMERecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref CognitoCustomDomainName
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - !ImportValue 
          !Sub "${AWS::StackName}-CognitoAliasTarget"
