AWSTemplateFormatVersion: "2010-09-09"
Description: Nested stack for Hosted Zone RecordSet

Parameters:
  GlobalCloudFrontHostedZoneId:
    Type: String
  HostedZoneId:
    Type: String
  SubDomain:
    Type: String

Resources:
  CloudFrontTypeARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref SubDomain
      Type: A
      AliasTarget:
        HostedZoneId: !Ref GlobalCloudFrontHostedZoneId
        DNSName: !ImportValue CloudFrontDistributionDomainName
        EvaluateTargetHealth: false # Important for CloudFront
