AWSTemplateFormatVersion: "2010-09-09"
Description: Nested stack for Hosted Zone RecordSet

Parameters:
  HostedZoneId:
    Type: String

Resources:
  CloudFrontVMSAliasRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: vms.alphinecodetech.click
      Type: A
      AliasTarget:
        HostedZoneId: !Ref GlobalCloudFrontHostedZoneId
        DNSName: !ImportValue CloudFrontDistributionDomainName
        EvaluateTargetHealth: false # Important for CloudFront

