AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SES Configuration for Visitor Management

Parameters:
  SysNotifEmailAddress:
    Type: String
    Description: Email address for SES notifications

Resources:
  VisitorManagementSESIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: !Ref SysNotifEmailAddress

  VisitorArrivalSESTemplate:
    Type: AWS::SES::Template
    Properties:
      Template:
        TemplateName: VisitorArrivalNotification
        SubjectPart: "Your visitor {{visitor_name}} has arrived!"
        TextPart: "Hello {{resident_givenName}},\n\nYour visitor {{visitor_name}} has arrived at the gate on {{arrival_time}}.\n\nPlease proceed to the reception area to meet them. \n\nThank you for using our visitor management system."
        HtmlPart: "<h1>Hello {{resident_givenName}},</h1><p>Your visitor <b>{{visitor_name}}</b> has arrived at the gate at <b>{{arrival_time}}</b>.</p><p>Please proceed to the reception area to meet them.</p><p>Thank you for using our visitor management system.</p>"

  VisitorDepartureSESTemplate:
    Type: AWS::SES::Template
    Properties:
      Template:
        TemplateName: VisitorDepartureNotification
        SubjectPart: "Your visitor {{visitor_name}} has departed."
        TextPart: "Hello {{resident_givenName}},\n\nThis is to confirm that your visitor {{visitor_name}} has successfully departed from the premises on {{departure_time}}. \n\nThank you for using our visitor management system."
        HtmlPart: "<h1>Hello {{resident_givenName}},</h1><p>This is to confirm that your visitor <b>{{visitor_name}}</b> has successfully departed from the premises at <b>{{departure_time}}</b>.</p><p>Thank you for using our visitor management system.</p>"

  VisitorInviteSESTemplate:
    Type: AWS::SES::Template
    Properties:
      Template:
        TemplateName: VisitorInviteNotification
        SubjectPart: "You're invited to visit!"
        TextPart: |
          Hello {{visitor_name}},

          You're invited by {{resident_fullName}} to visit on {{visit_date}}.

          If you have any questions, you can contact {{resident_givenName}} at {{resident_email}}.

          Please present this invitation upon arrival.

          We look forward to seeing you!
        HtmlPart: |
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <title>Your Visit Invitation</title>
          </head>
          <body>
            <h1>Hello {{visitor_name}},</h1>
            <p>You're invited by <b>{{resident_fullName}}</b> to visit on <b>{{visit_date}}</b>.</p>
            <p>If you have any questions, you can contact {{resident_givenName}} at 
            <a href="mailto:{{resident_email}}">{{resident_email}}</a>.</p>
            <p>Please present this invitation upon arrival:</p>
            <p style="text-align: center;">
              <img 
                src="{{visit_qrCodeImageURL}}" 
                alt="QR Code for Visit" 
                style="display: block; margin: 0 auto; border: 1px solid #ccc; max-width: 200px; height: auto;"
              >
            </p>
            <p>We look forward to seeing you!</p>
          </body>
          </html>

  VisitRequestApprovalSESTemplate:
    Type: AWS::SES::Template
    Properties:
      Template:
        TemplateName: VisitRequestApprovalNotification
        SubjectPart: "Your visit request has been approved!"
        TextPart: |
          Hello {{visitor_name}},

          Your visit request to {{resident_fullName}} on {{visit_date}} has been approved.

          Please present the attached QR code upon arrival for verification.

          We look forward to your visit!
        HtmlPart: |
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <title>Visit Request Approved</title>
          </head>
          <body>
            <h1>Hello {{visitor_name}},</h1>
            <p>Your visit request to <b>{{resident_fullName}}</b> on <b>{{visit_date}}</b> has been <span style="color: green;"><b>approved</b></span>.</p>
            <p>Please present the QR code below upon arrival:</p>
            <p style="text-align: center;">
              <img 
                src="{{visit_qrCodeImageURL}}" 
                alt="QR Code for Visit Approval" 
                style="display: block; margin: 0 auto; border: 1px solid #ccc; max-width: 200px; height: auto;"
              >
            </p>
            <p>We look forward to your visit!</p>
          </body>
          </html>

  VisitRequestDeclineSESTemplate:
    Type: AWS::SES::Template
    Properties:
      Template:
        TemplateName: VisitRequestDeclineNotification
        SubjectPart: "Your visit request has been declined"
        TextPart: |
          Hello {{visitor_name}},

          Unfortunately, your request to visit {{resident_fullName}} on {{visit_date}} has been declined.

          If you have any questions, please reach out to the resident directly.

          Thank you for your understanding.
        HtmlPart: |
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <title>Visit Request Declined</title>
          </head>
          <body>
            <h1>Hello {{visitor_name}},</h1>
            <p>We regret to inform you that your request to visit <b>{{resident_fullName}}</b> on <b>{{visit_date}}</b> has been <span style="color: red;"><b>declined</b></span>.</p>
            <p>If you have any questions, feel free to contact the resident directly.</p>
            <p>Thank you for your understanding.</p>
          </body>
          </html>

  VisitRequestNotificationForResident:
    Type: AWS::SES::Template
    Properties:
      Template:
        TemplateName: VisitRequestNotificationForResident
        SubjectPart: "New visit request from {{visitor_name}}"
        TextPart: |
          Hello,

          A new visit request has been submitted by {{visitor_name}} for {{visit_date}}.

          Visitor Details:
          Name: {{visitor_name}}
          Email: {{visitor_email}}
          Visit Date: {{visit_date}}

          Please log in to your resident portal to approve or decline this request.

          Thank you.
        HtmlPart: |
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <title>New Visit Request</title>
            <style>
              body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
              .container { max-width: 600px; margin: 20px auto; padding: 20px; border: 1px solid #ddd; border-radius: 8px; }
              .header { background-color: #f4f4f4; padding: 10px; text-align: center; border-bottom: 1px solid #ddd; }
              .details-table { width: 100%; border-collapse: collapse; margin-top: 20px; }
              .details-table th, .details-table td { padding: 10px; border: 1px solid #ddd; text-align: left; }
              .details-table th { background-color: #f9f9f9; width: 30%; }
              .button-container { text-align: center; margin-top: 20px; }
              .button-container a { display: inline-block; padding: 10px 20px; color: white; text-decoration: none; border-radius: 5px; }
              .approve-btn { background-color: #28a745; margin-right: 10px; }
              .decline-btn { background-color: #dc3545; }
              .note { margin-top: 20px; font-style: italic; color: #666; }
            </style>
          </head>
          <body>
            <div class="container">
              <div class="header">
                <h2>New Visit Request</h2>
              </div>
              <p>Hello,</p>
              <p>You have a new visit request from <strong>{{visitor_name}}</strong> for <strong>{{visit_date}}</strong> at <strong>{{visit_time}}</strong>.</p>
              
              <h3>Visitor Details:</h3>
              <table class="details-table">
                <tr>
                  <th>Name</th>
                  <td>{{visitor_name}}</td>
                </tr>
                <tr>
                  <th>Email</th>
                  <td>{{visitor_email}}</td>
                </tr>
              </table>

              <p class="note">Please log in to your resident portal to approve or decline this request.</p>
            </div>
          </body>
          </html>
