AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM template to create a Parameter Store entries

Parameters:
  SendEmailValue:
    Type: String
    Default: "false"
  StackName:
    Type: String
    Description: The name of the parent stack

Resources:
  SendEmailParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${StackName}/notification/send-email"
      Type: String
      Value: !Ref SendEmailValue
      Description: "Enable or disable email notifications"

Outputs:
  SendEmailParameterName:
    Description: "The SSM Parameter name"
    Value: !Ref SendEmailParameter

  SendEmailParameterValue:
    Description: "The value of the parameter"
    Value: !Ref SendEmailValue
