AWSTemplateFormatVersion: "2010-09-09"
Description: Nested stack for Verified Permissions Policy Store

Parameters:
  AdminGroupName:
    Type: String
  ResidentGroupName:
    Type: String
  GuardGroupName:
    Type: String

Resources:
  VisitorManagementPolicyStore:
    Type: AWS::VerifiedPermissions::PolicyStore
    Properties:
      Schema:
        CedarJson: |
          {
                "VisitorManagement": {
                    "entityTypes": {
                        "User": {
                            "memberOfTypes": [
                                "UserGroup"
                            ],
                            "shape": {
                                "type": "Record",
                                "attributes": {}
                            }
                        },
                        "Resource": {
                            "memberOfTypes": [],
                            "shape": {
                                "type": "Record",
                                "attributes": {}
                            }
                        },
                        "UserGroup": {
                            "memberOfTypes": [],
                            "shape": {
                                "type": "Record",
                                "attributes": {}
                            }
                        }
                    },
                    "actions": {
                        "showAdminBadge": {
                            "appliesTo": {
                                "context": {
                                    "type": "Record",
                                    "attributes": {}
                                },
                                "principalTypes": [
                                    "User"
                                ],
                                "resourceTypes": [
                                    "Resource"
                                ]
                            },
                            "memberOf": [
                                {
                                    "id": "UI",
                                    "type": "VisitorManagement::Action"
                                }
                            ]
                        },
                        "showGuardBadge": {
                            "appliesTo": {
                                "context": {
                                    "type": "Record",
                                    "attributes": {}
                                },
                                "principalTypes": [
                                    "User"
                                ],
                                "resourceTypes": [
                                    "Resource"
                                ]
                            },
                            "memberOf": [
                                {
                                    "id": "UI",
                                    "type": "VisitorManagement::Action"
                                }
                            ]
                        },
                        "searchVisitor": {
                            "appliesTo": {
                                "context": {
                                    "type": "Record",
                                    "attributes": {}
                                },
                                "principalTypes": [
                                    "User"
                                ],
                                "resourceTypes": [
                                    "Resource"
                                ]
                            },
                            "memberOf": [
                                {
                                    "id": "UI",
                                    "type": "VisitorManagement::Action"
                                }
                            ]
                        },
                        "registerVisitor": {
                            "appliesTo": {
                                "context": {
                                    "type": "Record",
                                    "attributes": {}
                                },
                                "principalTypes": [
                                    "User"
                                ],
                                "resourceTypes": [
                                    "Resource"
                                ]
                            },
                            "memberOf": [
                                {
                                    "id": "UI",
                                    "type": "VisitorManagement::Action"
                                }
                            ]
                        },
                        "inviteVisitor": {
                            "appliesTo": {
                                "context": {
                                    "type": "Record",
                                    "attributes": {}
                                },
                                "principalTypes": [
                                    "User"
                                ],
                                "resourceTypes": [
                                    "Resource"
                                ]
                            },
                            "memberOf": [
                                {
                                    "id": "UI",
                                    "type": "VisitorManagement::Action"
                                }
                            ]
                        },
                        "verifyVisitor": {
                            "appliesTo": {
                                "context": {
                                    "type": "Record",
                                    "attributes": {}
                                },
                                "principalTypes": [
                                    "User"
                                ],
                                "resourceTypes": [
                                    "Resource"
                                ]
                            },
                            "memberOf": [
                                {
                                    "id": "UI",
                                    "type": "VisitorManagement::Action"
                                }
                            ]
                        },
                        "browseVisitors": {
                            "appliesTo": {
                                "context": {
                                    "type": "Record",
                                    "attributes": {}
                                },
                                "principalTypes": [
                                    "User"
                                ],
                                "resourceTypes": [
                                    "Resource"
                                ]
                            },
                            "memberOf": [
                                {
                                    "id": "UI",
                                    "type": "VisitorManagement::Action"
                                }
                            ]
                        },
                        "UI": {
                            "memberOf": [],
                            "appliesTo": {
                                "context": {
                                    "type": "Record",
                                    "attributes": {}
                                },
                                "principalTypes": [],
                                "resourceTypes": []
                            }
                        },
                        "getPermissions": {
                            "memberOf": [
                                {
                                    "id": "API",
                                    "type": "VisitorManagement::Action"
                                }
                            ],
                            "appliesTo": {
                                "context": {
                                    "type": "Record",
                                    "attributes": {}
                                },
                                "principalTypes": [
                                    "UserGroup"
                                ],
                                "resourceTypes": [
                                    "Resource"
                                ]
                            }
                        },
                        "getVisitorsByResidentId": {
                            "memberOf": [
                                {
                                    "id": "API",
                                    "type": "VisitorManagement::Action"
                                }
                            ],
                            "appliesTo": {
                                "context": {
                                    "type": "Record",
                                    "attributes": {}
                                },
                                "principalTypes": [
                                    "UserGroup"
                                ],
                                "resourceTypes": [
                                    "Resource"
                                ]
                            }
                        },
                        "getVisitRequestsByResidentId": {
                            "memberOf": [
                                {
                                    "id": "API",
                                    "type": "VisitorManagement::Action"
                                }
                            ],
                            "appliesTo": {
                                "context": {
                                    "type": "Record",
                                    "attributes": {}
                                },
                                "principalTypes": [
                                    "UserGroup"
                                ],
                                "resourceTypes": [
                                    "Resource"
                                ]
                            }
                        },
                        "getVisitorByRegistrationId": {
                            "memberOf": [
                                {
                                    "id": "API",
                                    "type": "VisitorManagement::Action"
                                }
                            ],
                            "appliesTo": {
                                "context": {
                                    "type": "Record",
                                    "attributes": {}
                                },
                                "principalTypes": [
                                    "UserGroup"
                                ],
                                "resourceTypes": [
                                    "Resource"
                                ]
                            }
                        },
                        "getInviteByToken": {
                            "memberOf": [
                                {
                                    "id": "API",
                                    "type": "VisitorManagement::Action"
                                }
                            ],
                            "appliesTo": {
                                "context": {
                                    "type": "Record",
                                    "attributes": {}
                                },
                                "principalTypes": [
                                    "UserGroup"
                                ],
                                "resourceTypes": [
                                    "Resource"
                                ]
                            }
                        },
                        "getVisitRequestByToken": {
                            "memberOf": [
                                {
                                    "id": "API",
                                    "type": "VisitorManagement::Action"
                                }
                            ],
                            "appliesTo": {
                                "context": {
                                    "type": "Record",
                                    "attributes": {}
                                },
                                "principalTypes": [
                                    "UserGroup"
                                ],
                                "resourceTypes": [
                                    "Resource"
                                ]
                            }
                        },
                        "postVisitor": {
                            "memberOf": [
                                {
                                    "id": "API",
                                    "type": "VisitorManagement::Action"
                                }
                            ],
                            "appliesTo": {
                                "context": {
                                    "type": "Record",
                                    "attributes": {}
                                },
                                "principalTypes": [
                                    "UserGroup"
                                ],
                                "resourceTypes": [
                                    "Resource"
                                ]
                            }
                        },
                        "postInvite": {
                            "memberOf": [
                                {
                                    "id": "API",
                                    "type": "VisitorManagement::Action"
                                }
                            ],
                            "appliesTo": {
                                "context": {
                                    "type": "Record",
                                    "attributes": {}
                                },
                                "principalTypes": [
                                    "UserGroup"
                                ],
                                "resourceTypes": [
                                    "Resource"
                                ]
                            }
                        },
                        "postVisitRequest": {
                            "memberOf": [
                                {
                                    "id": "API",
                                    "type": "VisitorManagement::Action"
                                }
                            ],
                            "appliesTo": {
                                "context": {
                                    "type": "Record",
                                    "attributes": {}
                                },
                                "principalTypes": [
                                    "UserGroup"
                                ],
                                "resourceTypes": [
                                    "Resource"
                                ]
                            }
                        },
                        "API": {
                            "memberOf": [],
                            "appliesTo": {
                                "context": {
                                    "type": "Record",
                                    "attributes": {}
                                },
                                "principalTypes": [],
                                "resourceTypes": []
                            }
                        }
                    }
                }
            }
      ValidationSettings:
        Mode: STRICT

  AllowAdminGroupAccessPolicy:
    Type: AWS::VerifiedPermissions::Policy
    Properties:
      PolicyStoreId: !Ref VisitorManagementPolicyStore
      Definition:
        Static:
          Statement: !Sub |
            permit (
                principal in VisitorManagement::UserGroup::"${AdminGroupName}",
                action in
                    [VisitorManagement::Action::"browseVisitors",
                    VisitorManagement::Action::"inviteVisitor",
                    VisitorManagement::Action::"registerVisitor",
                    VisitorManagement::Action::"searchVisitor",
                    VisitorManagement::Action::"verifyVisitor",
                    VisitorManagement::Action::"showAdminBadge",
                    VisitorManagement::Action::"getPermissions",
                    VisitorManagement::Action::"getVisitorsByResidentId",
                    VisitorManagement::Action::"getVisitRequestsByResidentId",
                    VisitorManagement::Action::"getVisitorByRegistrationId",
                    VisitorManagement::Action::"getInviteByToken",
                    VisitorManagement::Action::"getVisitRequestByToken",
                    VisitorManagement::Action::"postVisitor",
                    VisitorManagement::Action::"postInvite",
                    VisitorManagement::Action::"postVisitRequest"],
                resource == VisitorManagement::Resource::"visitorResource"
            );
  AllowResidentGroupAccessPolicy:
    Type: AWS::VerifiedPermissions::Policy
    Properties:
      PolicyStoreId: !Ref VisitorManagementPolicyStore
      Definition:
        Static:
          Statement: !Sub |
            permit (
                principal in VisitorManagement::UserGroup::"${ResidentGroupName}",
                action in
                    [VisitorManagement::Action::"browseVisitors",
                    VisitorManagement::Action::"inviteVisitor",
                    VisitorManagement::Action::"registerVisitor",
                    VisitorManagement::Action::"getPermissions",
                    VisitorManagement::Action::"getVisitorsByResidentId",
                    VisitorManagement::Action::"getVisitRequestsByResidentId",
                    VisitorManagement::Action::"getInviteByToken",
                    VisitorManagement::Action::"getVisitRequestByToken",
                    VisitorManagement::Action::"postVisitor",
                    VisitorManagement::Action::"postInvite",
                    VisitorManagement::Action::"postVisitRequest"],
                resource == VisitorManagement::Resource::"visitorResource"
            );
  AllowGuardGroupAccessPolicy:
    Type: AWS::VerifiedPermissions::Policy
    Properties:
      PolicyStoreId: !Ref VisitorManagementPolicyStore
      Definition:
        Static:
          Statement: !Sub |
            permit (
                principal in VisitorManagement::UserGroup::"${GuardGroupName}",
                action in 
                    [VisitorManagement::Action::"verifyVisitor",
                    VisitorManagement::Action::"searchVisitor",
                    VisitorManagement::Action::"showGuardBadge",
                    VisitorManagement::Action::"getPermissions",
                    VisitorManagement::Action::"getVisitorsByResidentId",
                    VisitorManagement::Action::"getInviteByToken",
                    VisitorManagement::Action::"postVisitor",
                    VisitorManagement::Action::"getVisitRequestByToken"],
                resource == VisitorManagement::Resource::"visitorResource"
            );

Outputs:
  VisitorManagementPolicyStore:
    Value: !Ref VisitorManagementPolicyStore
    Export:
      Name: VisitorManagementPolicyStore
