AWSTemplateFormatVersion: "2010-09-09"

VisitorsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: VisitorsTable
    AttributeDefinitions:
      - AttributeName: registrationId
        AttributeType: S
    KeySchema:
      - AttributeName: registrationId
        KeyType: HASH
    BillingMode: PAY_PER_REQUEST

InviteLinksTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: InviteLinksTable
    AttributeDefinitions:
      - AttributeName: inviteToken
        AttributeType: S
    KeySchema:
      - AttributeName: inviteToken
        KeyType: HASH
    BillingMode: PAY_PER_REQUEST
    TimeToLiveSpecification:
      AttributeName:
