name: Deploy to Production

# Trigger the workflow only on push to the main branch
on:
  push:
    # branches:
    #   - main
    paths:
      - "backend/**"
      - "frontend/**"
      - "deploy_backend_and_infra.sh"
      - "deploy_frontend.sh"
      - ".github/workflows/deploy.yml"

env:
  AWS_REGION: ap-southeast-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  STACK_NAME: visitor-management
  DOMAIN_NAME: alphinecodetech.click
  SUB_DOMAIN: vms.alphinecodetech.click
  APP_FRONTEND_BASE_URL: https://vms.alphinecodetech.click
  COGNITO_CUSTOM_DOMAIN_NAME: login.vms.alphinecodetech.click
  COGNITO_ADMIN_INIT_PASSWORD: ${{ secrets.COGNITO_ADMIN_INIT_PASSWORD }}

jobs:
  plan-deploy-backend-and-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy Backend and Infra
        run: ./plan_deploy_backend_and_infra.sh

  deploy-backend-and-infra:
    runs-on: ubuntu-latest
    needs: plan-deploy-backend-and-infra
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy Backend and Infra
        run: ./plan_deploy_backend_and_infra.sh

  deploy-frontend:
    runs-on: ubuntu-latest
    # if: ${{ github.event.head_commit.message != 'skip frontend' }}
    needs: deploy-backend-and-infra
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Run deploy script
        run: ./deploy_frontend.sh
