name: Deploy to Production

# Trigger the workflow only on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Checks out your code in the repository

      - name: Set up Node.js (optional, if required for your deploy script)
        uses: actions/setup-node@v3 # Optional: Set up Node.js if your deploy script needs it

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run deploy script
        run: ./deploy.sh # Executes the deploy script
        # env:
        #   # Optional: Add environment variables if required for your deploy script
        #   # EXAMPLE_ENV_VAR: ${{ secrets.YOUR_SECRET }}
