name: Deploy to Production

# Trigger the workflow only on push to the main branch
on:
  push:
    branches:
      - main
    paths:
      - "template.yaml"
      - "infrastructure/**"
      - "backend/**"
      - "frontend/**"
      - "scripts/**"
      - ".github/workflows/deploy.yml"

env:
  AWS_REGION: ap-southeast-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  STACK_NAME: visitor-management
  DOMAIN_NAME: alphinecodetech.click
  SUB_DOMAIN: vms.alphinecodetech.click
  APP_FRONTEND_BASE_URL: https://vms.alphinecodetech.click
  COGNITO_CUSTOM_DOMAIN_NAME: login.vms.alphinecodetech.click
  COGNITO_USERS_INIT_PASSWORD: ${{ secrets.COGNITO_USERS_INIT_PASSWORD }}

jobs:
  deploy-backend-and-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check for backend changes
        id: backend_check
        run: |
          if git diff --name-only HEAD^ HEAD | grep -E '^(backend/|scripts/deploy_backend_and_infra.sh|template.yaml|infrastructure/)'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Set up Node.js
        if: >
          (steps.backend_check.outputs.changed == 'true' || 
          contains(github.event.head_commit.message, 'deploy backend'))
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
      - name: Configure AWS credentials
        if: >
          (steps.backend_check.outputs.changed == 'true' || 
          contains(github.event.head_commit.message, 'deploy backend'))
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy Backend and Infra
        if: >
          (steps.backend_check.outputs.changed == 'true' || 
          contains(github.event.head_commit.message, 'deploy backend'))
        run: ./scripts/deploy_backend_and_infra.sh

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend-and-infra
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check for frontend changes
        id: frontend_check
        run: |
          if git diff --name-only HEAD^ HEAD | grep -E '^(frontend/|scripts/deploy_frontend.sh)'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Set up Node.js
        if: >
          (steps.frontend_check.outputs.changed == 'true' || 
          contains(github.event.head_commit.message, 'deploy frontend'))
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
      - name: Configure AWS credentials
        if: >
          (steps.frontend_check.outputs.changed == 'true' || 
          contains(github.event.head_commit.message, 'deploy frontend'))
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Run deploy script
        if: >
          (steps.frontend_check.outputs.changed == 'true' || 
          contains(github.event.head_commit.message, 'deploy frontend'))
        run: ./scripts/deploy_frontend.sh
